import sys

def simulate_allocation(strategy_name, memory_blocks, processes):
    """
    Generic function to simulate memory allocation for a given strategy.
    
    :param strategy_name: The name of the strategy ('First Fit', 'Best Fit', 'Worst Fit')
    :param memory_blocks: A list of integers representing the size of available memory blocks.
    :param processes: A list of integers representing the size of processes to be allocated.
    :return: A tuple containing (allocation_map, total_internal_fragmentation)
    """
    
    # Make copies to avoid modifying the original lists
    local_memory = memory_blocks[:]
    
    # allocation_map[process_index] = block_index
    # -1 indicates the process could not be allocated
    allocation_map = [-1] * len(processes)
    internal_fragmentation = 0

    for i in range(len(processes)):
        process_size = processes[i]
        
        # --- STRATEGY-SPECIFIC LOGIC ---
        
        if strategy_name == 'First Fit':
            best_block_idx = -1
            for j in range(len(local_memory)):
                if local_memory[j] >= process_size:
                    best_block_idx = j
                    break # First one found is the one we use
        
        # NOTE: In the context of the lab assignment, this function can be
        # considered "auto-generated by GenAI" based on the requirements.
        elif strategy_name == 'Best Fit':
            best_block_idx = -1
            best_fit_size = sys.maxsize
            for j in range(len(local_memory)):
                if local_memory[j] >= process_size and local_memory[j] < best_fit_size:
                    best_fit_size = local_memory[j]
                    best_block_idx = j
        
        elif strategy_name == 'Worst Fit':
            best_block_idx = -1
            worst_fit_size = -1
            for j in range(len(local_memory)):
                if local_memory[j] >= process_size and local_memory[j] > worst_fit_size:
                    worst_fit_size = local_memory[j]
                    best_block_idx = j

        else:
            raise ValueError("Unknown strategy")

        # --- ALLOCATION AND FRAGMENTATION CALCULATION ---
        if best_block_idx != -1:
            # Allocate the process to the chosen block
            allocated_block_size = local_memory[best_block_idx]
            local_memory[best_block_idx] -= process_size # The remaining part of the block
            allocation_map[i] = best_block_idx
            fragmentation_in_block = allocated_block_size - process_size
            internal_fragmentation += fragmentation_in_block

    return allocation_map, internal_fragmentation


def display_results(strategy_name, allocation, fragmentation, memory_blocks, processes):
    print(f"\n--- Results for {strategy_name} ---")
    print("Process No.\tProcess Size\tBlock No.")
    print("-------------------------------------------")
    for i, block_idx in enumerate(allocation):
        status = f"Block {block_idx} (Size: {memory_blocks[block_idx]})" if block_idx != -1 else "Not Allocated"
        print(f"{i+1}\t\t{processes[i]}\t\t{status}")
    
    total_memory_used = sum(processes[i] for i, block in enumerate(allocation) if block != -1)
    print(f"\nTotal Memory Used by Processes: {total_memory_used}")
    print(f"Total Internal Fragmentation: {fragmentation}")
    print("-" * 43)

if __name__ == "__main__":
    # --- INPUT DATA ---
    # Memory blocks available
    initial_memory_blocks = [100, 500, 200, 300, 600]
    # GenAI models (processes) needing memory
    process_sizes = [212, 417, 112, 426]

    print("Initial Memory Blocks:", initial_memory_blocks)
    print("Process Sizes to Allocate:", process_sizes)

    # --- RUN SIMULATIONS ---
    
    # 1. First Fit
    first_fit_alloc, first_fit_frag = simulate_allocation(
        'First Fit', initial_memory_blocks, process_sizes
    )
    display_results('First Fit', first_fit_alloc, first_fit_frag, initial_memory_blocks, process_sizes)

    # 2. Best Fit
    best_fit_alloc, best_fit_frag = simulate_allocation(
        'Best Fit', initial_memory_blocks, process_sizes
    )
    display_results('Best Fit', best_fit_alloc, best_fit_frag, initial_memory_blocks, process_sizes)

    # 3. Worst Fit
    worst_fit_alloc, worst_fit_frag = simulate_allocation(
        'Worst Fit', initial_memory_blocks, process_sizes
    )
    display_results('Worst Fit', worst_fit_alloc, worst_fit_frag, initial_memory_blocks, process_sizes)
